global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # FreeAgentics application metrics
  - job_name: "freeagentics-app"
    static_configs:
      - targets: ["host.docker.internal:8000"] # FastAPI app
    metrics_path: "/metrics"
    scrape_interval: 5s

  # System metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 10s
