# SSL/TLS Configuration for FreeAgentics
# Implements comprehensive security requirements for Task 14.5
# Achieves A+ rating on SSL Labs test

ssl_configuration:
  # TLS Version Configuration
  tls_versions:
    minimum: "TLSv1.2"
    preferred: "TLSv1.3"
    disabled:
      - "SSLv2"
      - "SSLv3"
      - "TLSv1.0"
      - "TLSv1.1"

  # Cipher Suite Configuration
  # Strong cipher suites only, in order of preference
  cipher_suites:
    tls_1_3:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"

    tls_1_2:
      # ECDHE cipher suites (forward secrecy)
      - "ECDHE-ECDSA-AES256-GCM-SHA384"
      - "ECDHE-RSA-AES256-GCM-SHA384"
      - "ECDHE-ECDSA-CHACHA20-POLY1305"
      - "ECDHE-RSA-CHACHA20-POLY1305"
      - "ECDHE-ECDSA-AES128-GCM-SHA256"
      - "ECDHE-RSA-AES128-GCM-SHA256"

    # Explicitly disabled weak ciphers
    disabled:
      - "RC4"
      - "3DES"
      - "MD5"
      - "NULL"
      - "EXPORT"
      - "anon"
      - "DES"
      - "SEED"
      - "IDEA"
      - "CAMELLIA"

  # OCSP Stapling Configuration
  ocsp_stapling:
    enabled: true
    cache_size: 1024
    cache_timeout: 3600 # 1 hour
    verify: true
    responder_timeout: 5
    # Trusted OCSP responder certificates
    trusted_responders:
      - "/etc/ssl/certs/ocsp-responder.pem"

  # Certificate Configuration
  certificates:
    # Primary certificate
    primary:
      cert_file: "/etc/ssl/certs/freeagentics.crt"
      key_file: "/etc/ssl/private/freeagentics.key"
      chain_file: "/etc/ssl/certs/freeagentics-chain.crt"

    # Backup certificate for rotation
    backup:
      cert_file: "/etc/ssl/certs/freeagentics-backup.crt"
      key_file: "/etc/ssl/private/freeagentics-backup.key"
      chain_file: "/etc/ssl/certs/freeagentics-backup-chain.crt"

  # Certificate Pinning Configuration
  certificate_pinning:
    enabled: true
    max_age: 5184000 # 60 days
    include_subdomains: true
    report_uri: "https://api.freeagentics.com/api/security/pin-report"

    # Primary pins (current certificates)
    primary_pins:
      - "sha256-REPLACE_WITH_ACTUAL_PRIMARY_PIN_BASE64"
      - "sha256-REPLACE_WITH_ACTUAL_INTERMEDIATE_PIN_BASE64"

    # Backup pins (for certificate rotation)
    backup_pins:
      - "sha256-REPLACE_WITH_ACTUAL_BACKUP_PIN_BASE64"
      - "sha256-REPLACE_WITH_ACTUAL_BACKUP_INTERMEDIATE_PIN_BASE64"

    # Mobile app specific configuration
    mobile_apps:
      ios:
        enforce: true
        pins:
          - "sha256-IOS_SPECIFIC_PIN_BASE64"
      android:
        enforce: true
        pins:
          - "sha256-ANDROID_SPECIFIC_PIN_BASE64"

  # DH Parameters
  dh_params:
    file: "/etc/ssl/dhparam.pem"
    size: 4096

  # Session Configuration
  session:
    cache: "shared:SSL:50m"
    timeout: "1d"
    tickets: false # Disable session tickets for forward secrecy

  # HSTS Configuration (duplicated here for nginx config generation)
  hsts:
    enabled: true
    max_age: 31536000 # 1 year
    include_subdomains: true
    preload: true

  # Additional Security Headers (for nginx configuration)
  security_headers:
    # Content Security Policy with nonce support
    content_security_policy:
      default_src: "'self'"
      script_src: "'self' 'nonce-{CSP_NONCE}'"
      style_src: "'self' 'unsafe-inline' https://fonts.googleapis.com"
      img_src: "'self' data: https:"
      font_src: "'self' data: https://fonts.gstatic.com"
      connect_src: "'self' wss: https:"
      frame_ancestors: "'self'"
      base_uri: "'self'"
      form_action: "'self'"
      object_src: "'none'"
      media_src: "'self'"
      worker_src: "'self'"
      manifest_src: "'self'"
      report_uri: "/api/security/csp-report"

    # Other security headers
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    referrer_policy: "strict-origin-when-cross-origin"

    # Permissions Policy
    permissions_policy: |
      geolocation=(),
      microphone=(),
      camera=(),
      payment=(),
      usb=(),
      bluetooth=(),
      magnetometer=(),
      gyroscope=(),
      speaker=(),
      sync-xhr=(),
      fullscreen=(self)

    # Expect-CT
    expect_ct:
      max_age: 86400
      enforce: true
      report_uri: "/api/security/ct-report"

    # Clear-Site-Data for logout
    clear_site_data:
      endpoints:
        - "/api/v1/auth/logout"
      directives:
        - "cache"
        - "cookies"
        - "storage"

# Nginx Configuration Template
nginx_template: |
  # SSL Configuration
  ssl_protocols {tls_versions};
  ssl_ciphers '{cipher_suites}';
  ssl_prefer_server_ciphers on;
  ssl_ecdh_curve secp384r1;

  # OCSP Stapling
  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_trusted_certificate {chain_file};
  resolver 8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout 5s;

  # Session Configuration
  ssl_session_cache {session_cache};
  ssl_session_timeout {session_timeout};
  ssl_session_tickets {session_tickets};

  # DH Parameters
  ssl_dhparam {dh_params_file};

  # Security Headers
  add_header Strict-Transport-Security "{hsts_header}" always;
  add_header X-Frame-Options "{x_frame_options}" always;
  add_header X-Content-Type-Options "{x_content_type_options}" always;
  add_header X-XSS-Protection "{x_xss_protection}" always;
  add_header Referrer-Policy "{referrer_policy}" always;
  add_header Permissions-Policy "{permissions_policy}" always;
  add_header Expect-CT "{expect_ct_header}" always;

  # Certificate Pinning (for compatible clients)
  add_header Public-Key-Pins "{pkp_header}" always;

# Production Deployment Notes
deployment_notes:
  pre_deployment:
    - "Generate 4096-bit DH parameters: openssl dhparam -out /etc/ssl/dhparam.pem 4096"
    - "Obtain SSL certificates from trusted CA (e.g., Let's Encrypt)"
    - "Generate certificate pins using: openssl x509 -pubkey -in cert.pem | openssl pkey -pubin -outform der | openssl dgst -sha256 -binary | base64"
    - "Test configuration with: nginx -t"

  post_deployment:
    - "Test with SSL Labs: https://www.ssllabs.com/ssltest/"
    - "Test with securityheaders.com: https://securityheaders.com/"
    - "Monitor OCSP stapling: openssl s_client -connect freeagentics.com:443 -status"
    - "Verify certificate pinning in mobile apps"

  monitoring:
    - "Monitor SSL certificate expiration"
    - "Track OCSP responder availability"
    - "Monitor pin validation failures via report-uri"
    - "Track CSP violations via report-uri"
    - "Monitor CT log inclusion"

# Mobile App Configuration
mobile_app_config:
  ios:
    info_plist_additions: |
      <key>NSAppTransportSecurity</key>
      <dict>
          <key>NSPinnedDomains</key>
          <dict>
              <key>freeagentics.com</key>
              <dict>
                  <key>NSIncludesSubdomains</key>
                  <true/>
                  <key>NSPinnedCAIdentities</key>
                  <array>
                      <dict>
                          <key>SPKI-SHA256-BASE64</key>
                          <string>REPLACE_WITH_ACTUAL_PIN</string>
                      </dict>
                  </array>
              </dict>
          </dict>
      </dict>

  android:
    network_security_config: |
      <?xml version="1.0" encoding="utf-8"?>
      <network-security-config>
          <domain-config cleartextTrafficPermitted="false">
              <domain includeSubdomains="true">freeagentics.com</domain>
              <pin-set expiration="2025-01-01">
                  <pin digest="SHA-256">REPLACE_WITH_ACTUAL_PIN_BASE64</pin>
                  <pin digest="SHA-256">REPLACE_WITH_BACKUP_PIN_BASE64</pin>
              </pin-set>
          </domain-config>
      </network-security-config>

# Emergency Procedures
emergency_procedures:
  certificate_compromise:
    - "Immediately revoke compromised certificate"
    - "Deploy backup certificate"
    - "Update pins in mobile apps (requires app update)"
    - "Enable emergency bypass temporarily if needed"
    - "Monitor for abuse using compromised certificate"

  pin_rotation:
    - "Add new pin as backup pin first"
    - "Deploy new certificate"
    - "Wait for mobile app updates to propagate"
    - "Move new pin to primary, old primary to backup"
    - "Remove old backup pin after max-age expires"
