"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"

interface AboutModalProps {
  isOpen: boolean
  onClose: () => void
}

export default function AboutModal({ isOpen, onClose }: AboutModalProps) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50">
      <Card className="w-[90%] max-w-2xl max-h-[90vh] overflow-y-auto bg-gradient-to-br from-purple-950 to-indigo-950 border border-purple-700">
        <CardHeader>
          <CardTitle className="text-white">About CogniticNet</CardTitle>
        </CardHeader>
        <CardContent className="text-purple-100 space-y-4">
          <h2 className="text-xl font-semibold">Contact Information</h2>
          <p>Andrew Pashea</p>
          <p>Email: andrewpashea@activeinference.institute</p>

          <h2 className="text-xl font-semibold">Project Links</h2>
          <p>
            <a
              href="https://github.com/apashea/CogniticNet/"
              className="text-blue-300 hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              GitHub Repository
            </a>
          </p>
          <p>
            <a
              href="https://doi.org/10.5281/zenodo.15450213"
              className="text-blue-300 hover:underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              Zenodo Publication
            </a>
          </p>

          <h2 className="text-xl font-semibold">Description</h2>
          <p>
            CogniticNet is an interactive platform for creating and managing intelligent agents with persistent
            knowledge bases. The application enables users to design agents with unique knowledge graphs, visualize
            connections between knowledge elements, and observe how agents' understanding evolves over time. Through its
            intuitive interface, users can interact with agents, contribute to their knowledge bases, and explore the
            emergent properties of interconnected cognitive systems.
          </p>

          <h2 className="text-xl font-semibold">Version</h2>
          <p>0.0.1</p>

          <h2 className="text-xl font-semibold">License</h2>
          <p>Dual Licensed:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              Creative Commons CC BY-NC-SA license for non-commercial use
              <ul className="list-disc pl-5 space-y-1 mt-1 text-sm">
                <li>
                  <strong>BY</strong> - Attribution: Credit must be given to the original creator
                </li>
                <li>
                  <strong>NC</strong> - NonCommercial: May not be used for commercial purposes
                </li>
                <li>
                  <strong>SA</strong> - ShareAlike: Adaptations must be shared under the same terms
                </li>
              </ul>
            </li>
            <li>Commercial License available for proprietary applications</li>
          </ul>
          <p className="text-sm mt-1">All contributions require a Contributor License Agreement (CLA)</p>

          <h2 className="text-xl font-semibold mt-6">Disclaimer</h2>
          <div className="bg-purple-900/30 border border-purple-800 rounded-md p-3 text-sm">
            <p className="mb-2">
              DISCLAIMER: CogniticNet is currently in early development (version 0.0.1) and is provided for research and
              experimental purposes only. The information, knowledge, and interactions generated by agents within this
              application may be incomplete, inaccurate, or misleading. Users should not rely on any outputs from this
              system for critical decisions or as factual truth.
            </p>
            <p className="mb-2">
              By using CogniticNet, you acknowledge that you are doing so at your own risk and discretion. Neither
              Andrew Pashea, the Active Inference Institute, nor any contributors to this project shall be held liable
              for any damages, consequences, or misunderstandings arising from the use of this software.
            </p>
            <p>
              This application is provided "as is" without warranty of any kind, either expressed or implied, including,
              but not limited to, the implied warranties of merchantability and fitness for a particular purpose.
            </p>
          </div>
        </CardContent>
        <CardFooter className="flex justify-end border-t border-purple-800 pt-4">
          <Button onClick={onClose} className="bg-purple-700 hover:bg-purple-600">
            Get Started
          </Button>
        </CardFooter>
      </Card>
    </div>
  )
}
