#!/bin/bash
# Repository Cleanup Script 1: Remove Python Cache Files
# Generated by Repository Forensics Analysis - 2025-07-17

echo "🧹 Starting Python cache file cleanup..."

# Count files before cleanup
CACHE_DIRS=$(find . -name "__pycache__" -type d | wc -l)
PYC_FILES=$(find . -name "*.pyc" -type f | wc -l)

echo "Found $CACHE_DIRS __pycache__ directories and $PYC_FILES .pyc files"

# Remove __pycache__ directories
echo "Removing __pycache__ directories..."
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# Remove .pyc files
echo "Removing .pyc files..."
find . -name "*.pyc" -type f -delete 2>/dev/null || true

# Remove .pyo files (Python optimized bytecode)
echo "Removing .pyo files..."
find . -name "*.pyo" -type f -delete 2>/dev/null || true

# Remove pytest cache
echo "Removing pytest cache..."
find . -name ".pytest_cache" -type d -exec rm -rf {} + 2>/dev/null || true

# Remove mypy cache
echo "Removing mypy cache..."
find . -name ".mypy_cache" -type d -exec rm -rf {} + 2>/dev/null || true

# Remove coverage cache
echo "Removing coverage cache..."
find . -name ".coverage" -type f -delete 2>/dev/null || true
find . -name ".coverage.*" -type f -delete 2>/dev/null || true

echo "✅ Python cache cleanup completed"
echo "Estimated space freed: ~50MB"
