"""Type stubs for factory-boy library."""

from typing import Any, Callable
from typing import List as ListType
from typing import Type, TypeVar

T = TypeVar("T")

class Factory:
    class Meta:
        model: Any
    def __init__(self, **kwargs: Any) -> None: ...

def Sequence(fn: Callable[[int], Any]) -> Any: ...
def Faker(provider: str) -> Any: ...
def LazyFunction(fn: Callable[[], Any]) -> Any: ...
def List(items: ListType[Any]) -> ListType[Any]: ...
def SubFactory(factory_class: Type[Factory]) -> Any: ...
def post_generation(fn: Callable[..., Any]) -> Callable[..., Any]: ...
