"""Type stubs for strawberry-graphql library."""

from typing import Any, Callable, Type, TypeVar

T = TypeVar("T")

def type(cls: Type[T]) -> Type[T]: ...
def input(cls: Type[T]) -> Type[T]: ...
def field(fn: Callable[..., Any]) -> Callable[..., Any]: ...
def mutation(fn: Callable[..., Any]) -> Callable[..., Any]: ...

class Schema:
    def __init__(
        self, query: Any, mutation: Any = None, **kwargs: Any
    ) -> None: ...
