name: "Essential CI"
on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: actions/setup-node@v4
        with: { node-version: "20", cache: npm, cache-dependency-path: web/package-lock.json }
      - run: |
          pip install ruff bandit
          ruff check . && ruff format --check .
          bandit -r . -ll -x './web,./tests,./venv' || echo "⚠️  Security warnings"
      - working-directory: ./web
        run: npm ci && npm run lint && npm run build

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env: { POSTGRES_PASSWORD: testpass, POSTGRES_DB: freeagentics_test }
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - env: { DATABASE_URL: "postgresql://postgres:testpass@localhost:5432/freeagentics_test" }
        run: |
          pip install -r requirements-core.txt && pip install -e .
          python -m pytest tests/ -x --tb=short

  ready:
    needs: [quality, tests]
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 All essential checks passed - ready to merge!"
