# Docker Secrets Configuration for FreeAgentics Production
# This file defines how secrets are managed in Docker Swarm mode

version: "3.8"

secrets:
  # Database secrets
  postgres_password:
    external: true
    name: freeagentics_postgres_password
  
  postgres_user:
    external: true
    name: freeagentics_postgres_user
  
  # Redis secrets
  redis_password:
    external: true
    name: freeagentics_redis_password
  
  # Application secrets
  secret_key:
    external: true
    name: freeagentics_secret_key
  
  jwt_secret:
    external: true
    name: freeagentics_jwt_secret
  
  jwt_private_key:
    external: true
    name: freeagentics_jwt_private_key
  
  jwt_public_key:
    external: true
    name: freeagentics_jwt_public_key
  
  # Encryption secrets
  encryption_key:
    external: true
    name: freeagentics_encryption_key
  
  # SSL/TLS certificates
  ssl_certificate:
    external: true
    name: freeagentics_ssl_certificate
  
  ssl_private_key:
    external: true
    name: freeagentics_ssl_private_key
  
  ssl_ca_bundle:
    external: true
    name: freeagentics_ssl_ca_bundle
  
  # API keys (if needed)
  openai_api_key:
    external: true
    name: freeagentics_openai_api_key
  
  anthropic_api_key:
    external: true
    name: freeagentics_anthropic_api_key
  
  # Monitoring and alerting
  slack_webhook:
    external: true
    name: freeagentics_slack_webhook
  
  grafana_admin_password:
    external: true
    name: freeagentics_grafana_admin_password

# Example service configuration using secrets
services:
  backend:
    image: freeagentics:production
    secrets:
      - postgres_password
      - redis_password
      - secret_key
      - jwt_secret
      - encryption_key
    environment:
      # Read secrets from mounted files
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - ENCRYPTION_KEY_FILE=/run/secrets/encryption_key
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

# Commands to create secrets in Docker Swarm:
#
# docker secret create freeagentics_postgres_password postgres_password.txt
# docker secret create freeagentics_redis_password redis_password.txt
# docker secret create freeagentics_secret_key secret_key.txt
# docker secret create freeagentics_jwt_secret jwt_secret.txt
# docker secret create freeagentics_encryption_key encryption_key.txt
# docker secret create freeagentics_ssl_certificate ssl_cert.pem
# docker secret create freeagentics_ssl_private_key ssl_key.pem